# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [42]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key


# Configure gmaps
gmaps.configure(api_key=g_key)

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [43]:
heat_map_df = pd.read_csv("../WeatherPy/Retrieved_City_Weather_Data.csv")
heat_map_df.dropna(inplace = True) 
heat_map_df.head()

,Unnamed: 0,city,Temp,Humidity,Cloudiness,Wind,Country,Lat,Lon,Date
0,0,porirua,14.23,66.0,24.0,9.89,NZ,-41.1333,174.8500,1.653101e+09
1,1,itum-kale,6.91,87.0,36.0,1.95,RU,42.7356,45.5758,1.653101e+09
4,4,busselton,19.91,57.0,3.0,4.48,AU,-33.6500,115.3333,1.653101e+09
5,5,bredasdorp,10.02,84.0,37.0,2.74,ZA,-34.5322,20.0403,1.653101e+09
6,6,port alfred,16.00,75.0,100.0,2.33,ZA,-33.5906,26.8910,1.653101e+09

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [44]:
locations = heat_map_df[["Lat", "Lon"]]
weight = heat_map_df["Humidity"]

In [45]:
fig = gmaps.figure()
fig

Figure(layout=FigureLayout(height='420px'))

In [46]:
heat_layer = gmaps.heatmap_layer(locations, weights=weight, 
                                 dissipating=False, max_intensity=10,
                                 point_radius=1)
fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [47]:
heat_map_df.head(100)

,Unnamed: 0,city,Temp,Humidity,Cloudiness,Wind,Country,Lat,Lon,Date
0,0,porirua,14.23,66.0,24.0,9.89,NZ,-41.1333,174.8500,1.653101e+09
1,1,itum-kale,6.91,87.0,36.0,1.95,RU,42.7356,45.5758,1.653101e+09
4,4,busselton,19.91,57.0,3.0,4.48,AU,-33.6500,115.3333,1.653101e+09
5,5,bredasdorp,10.02,84.0,37.0,2.74,ZA,-34.5322,20.0403,1.653101e+09
6,6,port alfred,16.00,75.0,100.0,2.33,ZA,-33.5906,26.8910,1.653101e+09
...,...,...,...,...,...,...,...,...,...,...
103,103,husavik,7.97,83.0,77.0,1.94,IS,66.0449,-17.3389,1.653101e+09
104,104,betioky,17.05,64.0,49.0,2.31,MG,-23.7167,44.3833,1.653101e+09
105,105,saint-philippe,18.95,84.0,36.0,5.04,RE,-21.3585,55.7679,1.653101e+09
106,106,clyde river,-5.35,91.0,100.0,1.80,CA,70.4692,-68.5914,1.653101e+09
107,107,zeya,12.69,57.0,82.0,4.81,RU,53.7500,127.2667,1.653101e+09

In [50]:
new_data_file = heat_map_df.loc[(heat_map_df['Humidity']>=70) & (heat_map_df['Humidity']<=80) & (heat_map_df['Wind']<=10) & (heat_map_df['Cloudiness']==0)]
new_data_file.head(10)

,Unnamed: 0,city,Temp,Humidity,Cloudiness,Wind,Country,Lat,Lon,Date
87,87,chalmette,27.36,74.0,0.0,1.79,US,29.9427,-89.9634,1.653101e+09
108,108,saint-pierre,18.99,78.0,0.0,4.79,RE,-21.3393,55.4781,1.653101e+09
114,114,cabo san lucas,20.84,70.0,0.0,4.02,MX,22.8909,-109.9124,1.653101e+09
289,289,bonavista,5.09,75.0,0.0,2.57,CA,48.6499,-53.1147,1.653102e+09
349,349,port hardy,10.83,77.0,0.0,4.53,CA,50.6996,-127.4199,1.653102e+09
351,351,guerrero negro,17.58,77.0,0.0,5.77,MX,27.9769,-114.0611,1.653102e+09
379,379,caravelas,20.46,72.0,0.0,2.51,BR,-17.7125,-39.2481,1.653102e+09
390,390,zaraza,25.48,74.0,0.0,3.78,VE,9.3503,-65.3245,1.653102e+09
412,412,santiago,14.36,70.0,0.0,0.93,CL,-33.4569,-70.6483,1.653101e+09
461,461,camacha,16.72,77.0,0.0,6.62,PT,33.0833,-16.3333,1.653102e+09

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [ ]:
hotel_df = new_data_file.reset_index(drop=True)
hotel_df["Hotel Name"] = ""

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]